### ISSUE TITLE
Deleting save games on FalloutVR isn't permanent

### ISSUE THREAD

**Issue by mcdonnelldean** [Nexus-Mods/node-gamebryo-savegames#1]
When deleting save files, after starting the game, the save files that were deleted via vortex are not deleted. Checking vortex again shows the saves have returned.

#### To reproduce
1. load falloutvr in vortext
2. navigate to saves
3. delete all saves except the ones you want to play
4. start the remaining save via vortex

- The saves will show back up in vortex as the game loads
- The saves are present in the loaded game

**Comment by TanninOne** [comment]
This should be fixed in the meantime.
In the future, please report all Vortex issues to the Nexus-Mods/vortex repo
